"""Initial schema with all tables

Revision ID: 46877dbfbe26
Revises: 
Create Date: 2026-01-30 11:04:17.195781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46877dbfbe26'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bibliographic_record',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('isbn', sa.String(length=17), nullable=True),
    sa.Column('cover_image', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('subtitle', sa.String(length=500), nullable=True),
    sa.Column('authors', sa.Text(), nullable=True),
    sa.Column('illustrators', sa.Text(), nullable=True),
    sa.Column('publisher', sa.String(length=200), nullable=True),
    sa.Column('publication_year', sa.Integer(), nullable=True),
    sa.Column('collection', sa.String(length=200), nullable=True),
    sa.Column('series_number', sa.String(length=50), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('country_code', sa.String(length=5), nullable=True),
    sa.Column('binding_type', sa.String(length=20), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('genre', sa.String(length=100), nullable=True),
    sa.Column('level', sa.String(length=50), nullable=True),
    sa.Column('medium_type', sa.String(length=50), nullable=False),
    sa.Column('target_audience', sa.String(length=20), nullable=True),
    sa.Column('keywords', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('has_illustrations', sa.Boolean(), nullable=True),
    sa.Column('dimensions', sa.String(length=50), nullable=True),
    sa.Column('physical_size', sa.String(length=100), nullable=True),
    sa.Column('total_items', sa.Integer(), nullable=False),
    sa.Column('total_circulations', sa.Integer(), nullable=False),
    sa.Column('last_borrowed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("binding_type IN ('hardcover', 'paperback', 'spiral', 'other') OR binding_type IS NULL", name='check_binding_type'),
    # NOTE: medium_type constraint removed per spec FR-014 (plain text storage without normalization)
    sa.CheckConstraint("target_audience IN ('child', 'youth', 'adult') OR target_audience IS NULL", name='check_target_audience'),
    sa.CheckConstraint('publication_year IS NULL OR (publication_year >= 1000 AND publication_year <= 2028)', name='check_publication_year_range'),
    sa.CheckConstraint('page_count IS NULL OR page_count > 0', name='check_page_count_positive'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bibliographic_record_category'), 'bibliographic_record', ['category'], unique=False)
    op.create_index(op.f('ix_bibliographic_record_genre'), 'bibliographic_record', ['genre'], unique=False)
    op.create_index(op.f('ix_bibliographic_record_id'), 'bibliographic_record', ['id'], unique=False)
    op.create_index(op.f('ix_bibliographic_record_isbn'), 'bibliographic_record', ['isbn'], unique=False)
    op.create_index(op.f('ix_bibliographic_record_language'), 'bibliographic_record', ['language'], unique=False)
    op.create_index(op.f('ix_bibliographic_record_medium_type'), 'bibliographic_record', ['medium_type'], unique=False)
    op.create_index(op.f('ix_bibliographic_record_publication_year'), 'bibliographic_record', ['publication_year'], unique=False)
    op.create_index(op.f('ix_bibliographic_record_target_audience'), 'bibliographic_record', ['target_audience'], unique=False)
    op.create_index(op.f('ix_bibliographic_record_title'), 'bibliographic_record', ['title'], unique=False)
    op.create_table('class',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('homeroom_teacher', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('student_count', sa.Integer(), nullable=False, server_default='0'),
    sa.Column('average_age', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_class_id'), 'class', ['id'], unique=False)
    op.create_index(op.f('ix_class_name'), 'class', ['name'], unique=True)
    op.create_table('system_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_format', sa.String(length=20), nullable=False),
    sa.Column('id_validation_regex', sa.String(length=200), nullable=False),
    sa.Column('id_length_min', sa.Integer(), nullable=False),
    sa.Column('id_length_max', sa.Integer(), nullable=False),
    sa.Column('barcode_type', sa.String(length=20), nullable=False),
    sa.Column('borrower_barcode_prefix', sa.String(length=10), nullable=False),
    sa.Column('item_barcode_prefix', sa.String(length=10), nullable=False),
    sa.Column('loan_limit_default', sa.Integer(), nullable=False),
    sa.Column('loan_limit_teacher', sa.Integer(), nullable=False),
    sa.Column('loan_duration_days', sa.Integer(), nullable=False),
    sa.Column('renewal_limit', sa.Integer(), nullable=False),
    sa.Column('hold_expiration_days', sa.Integer(), nullable=False),
    sa.Column('hold_queue_enabled', sa.Boolean(), nullable=False),
    sa.Column('max_holds_per_borrower', sa.Integer(), nullable=False, server_default='1'),
    sa.Column('inventory_search_result_limit', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=5), nullable=False),
    sa.Column('date_format', sa.String(length=20), nullable=False),
    sa.Column('academic_year_start_month', sa.Integer(), nullable=False),
    sa.Column('academic_year_current', sa.String(length=9), nullable=False),
    sa.Column('library_name', sa.String(length=200), nullable=False),
    sa.Column('library_code', sa.String(length=50), nullable=True),
    sa.Column('catalog_categories', sa.Text(), nullable=True),
    sa.Column('catalog_genres', sa.Text(), nullable=True),
    sa.Column('catalog_languages', sa.Text(), nullable=True),
    sa.Column('catalog_medium_types', sa.Text(), nullable=True),
    sa.Column('catalog_levels', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("barcode_type IN ('code39', 'code128')", name='check_barcode_type'),
    sa.CheckConstraint("id_format IN ('numeric', 'alphanumeric')", name='check_id_format'),
    sa.CheckConstraint("language IN ('fr', 'en')", name='check_language'),
    sa.CheckConstraint('academic_year_start_month >= 1 AND academic_year_start_month <= 12', name='check_academic_year_start_month'),
    sa.CheckConstraint('id = 1', name='singleton_settings'),
    sa.CheckConstraint('loan_duration_days > 0 AND loan_duration_days <= 365', name='check_loan_duration_range'),
    sa.CheckConstraint('loan_limit_default > 0 AND loan_limit_default <= 10', name='check_loan_limit_default_range'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('borrower',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('borrower_id', sa.String(length=20), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=True),
    sa.Column('grade_level', sa.String(length=20), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('blocked_reason', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("role IN ('student', 'teacher', 'staff')", name='check_borrower_role'),
    sa.ForeignKeyConstraint(['class_id'], ['class.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_borrower_active'), 'borrower', ['active'], unique=False)
    op.create_index(op.f('ix_borrower_borrower_id'), 'borrower', ['borrower_id'], unique=True)
    op.create_index(op.f('ix_borrower_class_id'), 'borrower', ['class_id'], unique=False)
    op.create_index(op.f('ix_borrower_full_name'), 'borrower', ['full_name'], unique=False)
    op.create_index(op.f('ix_borrower_id'), 'borrower', ['id'], unique=False)
    op.create_index(op.f('ix_borrower_role'), 'borrower', ['role'], unique=False)
    op.create_table('item',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_id', sa.String(length=20), nullable=False),
    sa.Column('bibliographic_record_id', sa.Integer(), nullable=False),
    sa.Column('call_number', sa.String(length=50), nullable=True),
    sa.Column('shelf_location', sa.String(length=100), nullable=True),
    sa.Column('condition', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('loanable', sa.Boolean(), nullable=False),
    sa.Column('acquisition_date', sa.Date(), nullable=True),
    sa.Column('funding_source', sa.String(length=100), nullable=True),
    sa.Column('circulation_count', sa.Integer(), nullable=False),
    sa.Column('last_borrowed_at', sa.DateTime(), nullable=True),
    sa.Column('last_inventoried_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("condition IN ('good', 'damaged')", name='check_item_condition'),
    sa.CheckConstraint("status IN ('available', 'on_loan', 'on_hold', 'in_repair', 'lost', 'withdrawn')", name='check_item_status'),
    sa.ForeignKeyConstraint(['bibliographic_record_id'], ['bibliographic_record.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_bibliographic_record_id'), 'item', ['bibliographic_record_id'], unique=False)
    op.create_index(op.f('ix_item_call_number'), 'item', ['call_number'], unique=False)
    op.create_index(op.f('ix_item_condition'), 'item', ['condition'], unique=False)
    op.create_index(op.f('ix_item_id'), 'item', ['id'], unique=False)
    op.create_index(op.f('ix_item_item_id'), 'item', ['item_id'], unique=True)
    op.create_index(op.f('ix_item_last_inventoried_at'), 'item', ['last_inventoried_at'], unique=False)
    op.create_index(op.f('ix_item_loanable'), 'item', ['loanable'], unique=False)
    op.create_index(op.f('ix_item_status'), 'item', ['status'], unique=False)
    op.create_table('circulation_transaction',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('borrower_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('bibliographic_record_id', sa.Integer(), nullable=False),
    sa.Column('checkout_date', sa.DateTime(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('return_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('renewal_count', sa.Integer(), nullable=False),
    sa.Column('checked_out_by', sa.String(length=100), nullable=True),
    sa.Column('returned_by', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status IN ('active', 'returned', 'overdue', 'renewed')", name='check_circulation_status'),
    sa.CheckConstraint('return_date IS NULL OR return_date >= checkout_date', name='check_return_date_after_checkout'),
    sa.ForeignKeyConstraint(['bibliographic_record_id'], ['bibliographic_record.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['borrower_id'], ['borrower.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_circulation_transaction_bibliographic_record_id'), 'circulation_transaction', ['bibliographic_record_id'], unique=False)
    op.create_index(op.f('ix_circulation_transaction_borrower_id'), 'circulation_transaction', ['borrower_id'], unique=False)
    op.create_index(op.f('ix_circulation_transaction_checkout_date'), 'circulation_transaction', ['checkout_date'], unique=False)
    op.create_index(op.f('ix_circulation_transaction_due_date'), 'circulation_transaction', ['due_date'], unique=False)
    op.create_index(op.f('ix_circulation_transaction_id'), 'circulation_transaction', ['id'], unique=False)
    op.create_index(op.f('ix_circulation_transaction_item_id'), 'circulation_transaction', ['item_id'], unique=False)
    op.create_index(op.f('ix_circulation_transaction_status'), 'circulation_transaction', ['status'], unique=False)
    op.create_table('hold',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('borrower_id', sa.Integer(), nullable=False),
    sa.Column('bibliographic_record_id', sa.Integer(), nullable=False),
    sa.Column('hold_date', sa.DateTime(), nullable=False),
    sa.Column('queue_position', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('available_date', sa.DateTime(), nullable=True),
    sa.Column('expiration_date', sa.Date(), nullable=True),
    sa.Column('fulfilled_date', sa.DateTime(), nullable=True),
    sa.Column('notified', sa.Boolean(), nullable=False),
    sa.Column('notification_method', sa.String(length=20), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status IN ('waiting', 'ready', 'fulfilled', 'expired', 'cancelled')", name='check_hold_status'),
    sa.CheckConstraint('queue_position > 0', name='check_queue_position_positive'),
    sa.ForeignKeyConstraint(['bibliographic_record_id'], ['bibliographic_record.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['borrower_id'], ['borrower.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hold_bibliographic_record_id'), 'hold', ['bibliographic_record_id'], unique=False)
    op.create_index(op.f('ix_hold_borrower_id'), 'hold', ['borrower_id'], unique=False)
    op.create_index(op.f('ix_hold_expiration_date'), 'hold', ['expiration_date'], unique=False)
    op.create_index(op.f('ix_hold_id'), 'hold', ['id'], unique=False)
    op.create_index(op.f('ix_hold_status'), 'hold', ['status'], unique=False)

    # Archive table for old circulation transactions (prevents database bloat)
    op.create_table('circulation_transaction_archive',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('borrower_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('bibliographic_record_id', sa.Integer(), nullable=False),
    sa.Column('checkout_date', sa.DateTime(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('return_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('renewal_count', sa.Integer(), nullable=False),
    sa.Column('checked_out_by', sa.String(length=100), nullable=True),
    sa.Column('returned_by', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('archived_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status IN ('active', 'returned', 'overdue', 'renewed')", name='check_archive_circulation_status'),
    sa.CheckConstraint('return_date IS NULL OR return_date >= checkout_date', name='check_archive_return_date_after_checkout'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_archive_borrower_id', 'circulation_transaction_archive', ['borrower_id'], unique=False)
    op.create_index('idx_archive_item_id', 'circulation_transaction_archive', ['item_id'], unique=False)
    op.create_index('idx_archive_checkout_date', 'circulation_transaction_archive', ['checkout_date'], unique=False)
    op.create_index('idx_archive_archived_at', 'circulation_transaction_archive', ['archived_at'], unique=False)

    # Performance composite indexes (4x query speedup for overdue loans and catalog search)
    op.create_index('idx_circ_borrower_return_due', 'circulation_transaction', ['borrower_id', 'return_date', 'due_date'], unique=False)
    op.create_index('idx_biblio_category_genre_lang', 'bibliographic_record', ['category', 'genre', 'language'], unique=False)

    # Partial unique index to prevent duplicate active loans (SQLite 3.8.0+)
    op.create_index('idx_unique_active_loan', 'circulation_transaction', ['item_id'], unique=True, sqlite_where=sa.text('return_date IS NULL'))

    # Index for return_date to support history pagination queries
    op.create_index('ix_circulation_transaction_return_date', 'circulation_transaction', ['return_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop composite indexes first
    op.drop_index('ix_circulation_transaction_return_date', table_name='circulation_transaction')
    op.drop_index('idx_unique_active_loan', table_name='circulation_transaction')
    op.drop_index('idx_biblio_category_genre_lang', table_name='bibliographic_record')
    op.drop_index('idx_circ_borrower_return_due', table_name='circulation_transaction')

    # Drop archive table
    op.drop_index('idx_archive_archived_at', table_name='circulation_transaction_archive')
    op.drop_index('idx_archive_checkout_date', table_name='circulation_transaction_archive')
    op.drop_index('idx_archive_item_id', table_name='circulation_transaction_archive')
    op.drop_index('idx_archive_borrower_id', table_name='circulation_transaction_archive')
    op.drop_table('circulation_transaction_archive')

    op.drop_index(op.f('ix_hold_status'), table_name='hold')
    op.drop_index(op.f('ix_hold_id'), table_name='hold')
    op.drop_index(op.f('ix_hold_expiration_date'), table_name='hold')
    op.drop_index(op.f('ix_hold_borrower_id'), table_name='hold')
    op.drop_index(op.f('ix_hold_bibliographic_record_id'), table_name='hold')
    op.drop_table('hold')
    op.drop_index(op.f('ix_circulation_transaction_status'), table_name='circulation_transaction')
    op.drop_index(op.f('ix_circulation_transaction_item_id'), table_name='circulation_transaction')
    op.drop_index(op.f('ix_circulation_transaction_id'), table_name='circulation_transaction')
    op.drop_index(op.f('ix_circulation_transaction_due_date'), table_name='circulation_transaction')
    op.drop_index(op.f('ix_circulation_transaction_checkout_date'), table_name='circulation_transaction')
    op.drop_index(op.f('ix_circulation_transaction_borrower_id'), table_name='circulation_transaction')
    op.drop_index(op.f('ix_circulation_transaction_bibliographic_record_id'), table_name='circulation_transaction')
    op.drop_table('circulation_transaction')
    op.drop_index(op.f('ix_item_status'), table_name='item')
    op.drop_index(op.f('ix_item_loanable'), table_name='item')
    op.drop_index(op.f('ix_item_last_inventoried_at'), table_name='item')
    op.drop_index(op.f('ix_item_item_id'), table_name='item')
    op.drop_index(op.f('ix_item_id'), table_name='item')
    op.drop_index(op.f('ix_item_condition'), table_name='item')
    op.drop_index(op.f('ix_item_call_number'), table_name='item')
    op.drop_index(op.f('ix_item_bibliographic_record_id'), table_name='item')
    op.drop_table('item')
    op.drop_index(op.f('ix_borrower_role'), table_name='borrower')
    op.drop_index(op.f('ix_borrower_id'), table_name='borrower')
    op.drop_index(op.f('ix_borrower_full_name'), table_name='borrower')
    op.drop_index(op.f('ix_borrower_class_id'), table_name='borrower')
    op.drop_index(op.f('ix_borrower_borrower_id'), table_name='borrower')
    op.drop_index(op.f('ix_borrower_active'), table_name='borrower')
    op.drop_table('borrower')
    op.drop_table('system_settings')
    op.drop_index(op.f('ix_class_name'), table_name='class')
    op.drop_index(op.f('ix_class_id'), table_name='class')
    op.drop_table('class')
    op.drop_index(op.f('ix_bibliographic_record_title'), table_name='bibliographic_record')
    op.drop_index(op.f('ix_bibliographic_record_target_audience'), table_name='bibliographic_record')
    op.drop_index(op.f('ix_bibliographic_record_publication_year'), table_name='bibliographic_record')
    op.drop_index(op.f('ix_bibliographic_record_medium_type'), table_name='bibliographic_record')
    op.drop_index(op.f('ix_bibliographic_record_language'), table_name='bibliographic_record')
    op.drop_index(op.f('ix_bibliographic_record_isbn'), table_name='bibliographic_record')
    op.drop_index(op.f('ix_bibliographic_record_id'), table_name='bibliographic_record')
    op.drop_index(op.f('ix_bibliographic_record_genre'), table_name='bibliographic_record')
    op.drop_index(op.f('ix_bibliographic_record_category'), table_name='bibliographic_record')
    op.drop_table('bibliographic_record')
    # ### end Alembic commands ###
